name: "Ism7MQTT"
description: "Addon for direct communication with a Wolf ISM7 module"
version: "1.0.7"
slug: "ism7mqtt"
init: false
url: https://github.com/b3nn0/hassio-addon-ism7mqtt
arch:
  - aarch64
  - amd64
  - armv7
  #- armhf
  #- i386
map:
  - "config:ro"
discovery:
  - mqtt
services:
  - "mqtt:need"


options:
  #ism7_ip: ""
  #ism7_password: ""
  device_name: Wolf
  #parameter_json: ""
  interval: 60
  debug_logging: False
  

schema:
  ism7_ip: str
  ism7_password: password
  device_name: str
  parameter_json: str
  interval: int
  debug_logging: bool
  
  
